-- MySQL Script generated by MySQL Workbench
-- 10/04/17 19:52:25
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entidad` (
  `entidadID` INT NOT NULL AUTO_INCREMENT,
  `nombreInstitucion` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(150) NOT NULL,
  `encargado` INT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `ciudad` VARCHAR(25) NOT NULL,
  `departamento` VARCHAR(15) NOT NULL,
  `latitud` FLOAT NULL,
  `longitud` FLOAT NULL,
  `horario` VARCHAR(200) NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`entidadID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Institucion` (
  `institucionID` INT NOT NULL,
  `tipoInstitucion` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`institucionID`),
  INDEX `fk_Institucion_Entidad1_idx` (`institucionID` ASC),
  CONSTRAINT `fk_Institucion_Entidad1`
    FOREIGN KEY (`institucionID`)
    REFERENCES `mydb`.`Entidad` (`entidadID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `usuarioID` INT NOT NULL AUTO_INCREMENT,
  `tipoUsuario` TINYINT NOT NULL,
  `cargo` VARCHAR(45) NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `primerAp` VARCHAR(100) NOT NULL,
  `segundoAp` VARCHAR(100) NULL,
  `telefono` VARCHAR(15) NULL,
  `correo` VARCHAR(80) NULL,
  `nombreUsuario` VARCHAR(15) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `estado` TINYINT NOT NULL,
  `institucionID` INT NOT NULL,
  PRIMARY KEY (`usuarioID`),
  INDEX `fk_Usuario_Institucion1_idx` (`institucionID` ASC),
  CONSTRAINT `fk_Usuario_Institucion1`
    FOREIGN KEY (`institucionID`)
    REFERENCES `mydb`.`Institucion` (`institucionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal` (
  `sucursalID` INT NOT NULL,
  `entidadID` INT NOT NULL,
  PRIMARY KEY (`sucursalID`),
  INDEX `fk_Sucursal_Entidad1_idx` (`sucursalID` ASC),
  INDEX `fk_Sucursal_Institucion1_idx` (`entidadID` ASC),
  CONSTRAINT `fk_Sucursal_Entidad1`
    FOREIGN KEY (`sucursalID`)
    REFERENCES `mydb`.`Entidad` (`entidadID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_Institucion1`
    FOREIGN KEY (`entidadID`)
    REFERENCES `mydb`.`Institucion` (`institucionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `categoriaID` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`categoriaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tramite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tramite` (
  `tramiteID` INT NOT NULL AUTO_INCREMENT,
  `nombreTramite` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `estado` TINYINT NOT NULL,
  `Institucion_idInstitucion` INT NOT NULL,
  `Institucion_Entidad_idEntidad` INT NOT NULL,
  `categoriaID` INT NOT NULL,
  `entidadID` INT NOT NULL,
  PRIMARY KEY (`tramiteID`),
  INDEX `fk_Tramite_Categoria1_idx` (`categoriaID` ASC),
  INDEX `fk_Tramite_Institucion1_idx` (`entidadID` ASC),
  CONSTRAINT `fk_Tramite_Categoria1`
    FOREIGN KEY (`categoriaID`)
    REFERENCES `mydb`.`Categoria` (`categoriaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tramite_Institucion1`
    FOREIGN KEY (`entidadID`)
    REFERENCES `mydb`.`Institucion` (`institucionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Requisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Requisito` (
  `requisitoID` INT NOT NULL AUTO_INCREMENT,
  `nombreRequisito` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`requisitoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TramiteRequisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TramiteRequisito` (
  `tramiteRequisitoID` INT NOT NULL AUTO_INCREMENT,
  `tramiteID` INT NOT NULL,
  `requisitoID` INT NOT NULL,
  PRIMARY KEY (`tramiteRequisitoID`),
  INDEX `fk_TramiteRequisito_Tramite1_idx` (`tramiteID` ASC),
  INDEX `fk_TramiteRequisito_Requisito1_idx` (`requisitoID` ASC),
  CONSTRAINT `fk_TramiteRequisito_Tramite1`
    FOREIGN KEY (`tramiteID`)
    REFERENCES `mydb`.`Tramite` (`tramiteID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TramiteRequisito_Requisito1`
    FOREIGN KEY (`requisitoID`)
    REFERENCES `mydb`.`Requisito` (`requisitoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consejo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consejo` (
  `consejoID` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `idUsuarioFacebook` VARCHAR(100) NULL,
  `tramiteID` INT NOT NULL,
  `requisitoID` INT NOT NULL,
  PRIMARY KEY (`consejoID`),
  INDEX `fk_Consejo_Tramite1_idx` (`tramiteID` ASC),
  INDEX `fk_Consejo_Requisito1_idx` (`requisitoID` ASC),
  CONSTRAINT `fk_Consejo_Tramite1`
    FOREIGN KEY (`tramiteID`)
    REFERENCES `mydb`.`Tramite` (`tramiteID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consejo_Requisito1`
    FOREIGN KEY (`requisitoID`)
    REFERENCES `mydb`.`Requisito` (`requisitoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
